node{
    docker.image('maven:3.5.4-alpine').inside('-v /root/.m2:/root/.m2'){
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') {
            sh 'mvn test'
            junit 'target/surefire-reports/*.xml'
        }
        stage('Deliver') {
            sh './jenkins/scripts/deliver.sh'
        }
    }
    
}